In [3]:
import numpy as np

In [4]:
lista = [1,2,3,4,5,6,7,8,9]
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr[0]

1

In [10]:
arr[0]+arr[5]

7

In [13]:
matriz[0,1]

2

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
 
arr[2:6]

array([3, 4, 5, 6])

In [20]:
arr[:3]

array([1, 2, 3])

In [21]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[::3]

array([1, 4, 7])

In [24]:
arr[-3]

7

In [25]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [43]:
matriz_3d = np.array([[[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]],

                      [[13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]]])
matriz_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [44]:
matriz_3d[0,1]

array([5, 6, 7, 8])

In [50]:
matriz_3d[1,:,2]

array([15, 19, 23])