In [1]:
import numpy as np

Scalar tiene una sola dimension, 

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

Vector cuenta con 2 dimensiones, como lo es una lista 

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

Una matriz cuenta con 3 dimensiones

In [9]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

El tensor cuenta con 4 dimensiones 

In [8]:
tensor = np.array([[[1,2,3],[4,5,6],[0,2,45]],[[1,2,3],[4,5,6],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 0  2 45]]]


3

#Agregar o eliminar dimensiones 'ndim', 'axis','squeeze'

Para agregar dimensiones al array dado usamos 'ndim'

In [11]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

Para expandir una sola dimension usamos 'axis', el '0' significa que quiero expandir una sola dimension a columna ([[1 2 3]]), si lo cambiamos por un '1' significa expandir una dimension a nivel filas ([[1] [2] [3]])

In [17]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

Para reducir las dimensiones que no estoy usando y quedarme solo con el que tiene información uso: 'squeeze'

In [15]:
print(vector,vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
