In [1]:
import numpy as np

Este metodo para crear un array de python no funciona en numpy

In [ ]:
list(range(0,10))

Para crear un array correctamente usamos np.arange([inicio],[fin -1],['slicing' de cuanto en cuanto])

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Cera un array en 0 que sirve por ejemplo para definir una estructura

In [7]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

linspace se usa para crear una distribucion ordenada de los numeros dados linspace([desde],[hasta],[cuantos])

In [10]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Para crear una matriz con un numero de nuestra preferencia usamos np.full(([filas],[columnas]),[numero que queremos])

In [19]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

np.eye crea una estructura lineal de 1's atraves de los arrays que le indicas que quieres 

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Para generar un numero, una serie de numeros o una matriz de numeros aleatorios usamos np.random.rand([con un solo numero, crea esa cantidad de numeros aleatorios],[pasando este paramentro crea una matriz del numero inicial como columnas y el numero final como filas]) si no recibe ningun parametro devuelve un numero aleatorio cada vez que esta funcion se ejecuta

In [12]:
np.random.rand()

0.6115447947136913

In [14]:
np.random.rand(4)

array([0.09782436, 0.9281225 , 0.8368096 , 0.90872621])

In [15]:
np.random.rand(4,4)

array([[0.51014201, 0.5786304 , 0.92082886, 0.43820458],
       [0.34554187, 0.27006061, 0.68444649, 0.09340661],
       [0.39614184, 0.98926529, 0.08228151, 0.99603748],
       [0.01083885, 0.4751526 , 0.95858218, 0.48773268]])

Para crear un numero aleatorio int entre un rango de numeros usamos: np.random.randinit([desde],[hasta])

In [16]:
np.random.randint(1,15)

9

Para llevarlo a que cree una matriz de numeros aleatorios entre un rango de numeros usamos np.random.randint([desde],[hasta],([filas],[columnas]))

In [17]:
np.random.randint(1,100,(10,9))

array([[99, 10, 74, 62, 74, 18, 15, 72, 72],
       [35, 32, 29, 82, 92, 35, 37, 22, 57],
       [99, 79, 73, 83, 65, 76, 77, 91,  7],
       [19, 73, 88, 11,  6,  9,  1, 91, 35],
       [ 6, 52, 45, 10, 59, 15, 75, 55, 33],
       [54,  9, 99, 76, 61,  4, 84, 32, 95],
       [ 7, 41,  6, 33, 44, 97, 52, 91, 69],
       [18, 88,  2, 61, 54, 19, 49, 52, 29],
       [19, 99, 29,  6,  1, 23, 93, 57, 44],
       [31, 16,  3, 84, 80, 50, 87, 10, 89]])