In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))
arr

array([[9, 4],
       [7, 2],
       [3, 7]])

Usando shape podemos saber que tan grande es el array con el que estoy trabajando, devolviendonos ([cantidad de filas],[cantidad de columnas])

In [3]:
arr.shape

(3, 2)

In [6]:
arr

array([[9, 4],
       [7, 2],
       [3, 7]])

Reshape retorna el contenido de un array con los mismos datos pero diferente forma.

In [13]:
arr.reshape(1,6)


array([9, 4, 7, 2, 3, 7])

In [14]:
arr.reshape(2,3)

array([[9, 4, 7],
       [2, 3, 7]])

In [15]:
np.reshape(arr,(1,6))

array([[9, 4, 7, 2, 3, 7]])

In [19]:
arr

array([[9, 4],
       [7, 2],
       [3, 7]])

Puede reorganizar la estructura como lo hace el lenguaje 'C' por filas pasamos el parametro 'C' siempre respetando la cantidad de valores que tiene el array

In [18]:
np.reshape(arr,(2,3),'C')

array([[9, 4, 7],
       [2, 3, 7]])

Puede reorganizar la estructura como lo hace el lenguaje 'Fortran' por columnas pasamos el parametro 'F', siempre respetando la cantidad de valores que tiene el array

In [16]:
np.reshape(arr,(2,3),'F')

array([[9, 3, 2],
       [7, 4, 7]])

Puede reorganizar la estructura como lo hace el guardado de datos en mi sistema pasando 'A' definiendo de manera aleatoria cual usara, este no me da la visibilidad de saber que formato esta usando por lo que se recomienda el uso de 'C' o 'A' siempre respetando la cantidad de valores que tiene el array

In [17]:
np.reshape(arr,(2,3),'A')

array([[9, 4, 7],
       [2, 3, 7]])