In [4]:
import numpy as np

Lo que estoy haciendo aqui es diciendole a numpy que me de un array de 10 numeros random int de entre el 1 y el 20

In [5]:
arr = np.random.randint(1,20,10)

y aca le pido que me restructure el array en una matriz de 2 filas con 5 elementos cada uno

In [6]:
matriz = arr.reshape(2,5)
matriz

array([[18, 17, 13,  5,  7],
       [19,  8,  9,  9, 18]])

In [7]:
arr

array([18, 17, 13,  5,  7, 19,  8,  9,  9, 18])

In [8]:
arr.max()

19

In [11]:
matriz

array([[18, 17, 13,  5,  7],
       [19,  8,  9,  9, 18]])

Le puedo pasar como parametro si quiero que me de el maximo por '0' (columnas) o '1' (filas), 

In [16]:
matriz.max(0)

array([19, 17, 13,  9, 18])

In [17]:
matriz.max(1)

array([18, 19])

Me devuelve el indice donde se encuentra el valor en donde se encuentra el valor maximo y con argumento '0' devuelve el maximo por columnas o '1' el maximo por filas

In [18]:
arr.argmax()

5

In [20]:
matriz.argmax(1)

array([0, 0])

In [21]:
arr.min()

5

In [22]:
matriz.min(0)

array([18,  8,  9,  5,  7])

In [23]:
matriz.min(1)

array([5, 8])

Ptp devuelve la diferencia entre el valor mas alto menos el valor mas bajo y tambien funciona con los parametros '0' columnas y '1' filas para matrices

In [25]:
arr

array([18, 17, 13,  5,  7, 19,  8,  9,  9, 18])

In [24]:
arr.ptp()

14

In [27]:
matriz.ptp(0)

array([ 1,  9,  4,  4, 11])

In [28]:
matriz.ptp(1)

array([13, 11])

El percentil es una medida estadística la cual divide una serie de datos ordenados de menor a mayor en cien partes iguales. Se trata de un indicador que busca mostrar la proporción de la serie de datos que queda por debajo de su valor. a np.percentile([recibe el arr], [recibe el numero base de percentil])

In [33]:
np.sort(arr)

array([ 5,  7,  8,  9,  9, 13, 17, 18, 18, 19])

In [34]:
np.percentile(arr,50)

11.0

median entrega la mediana de un array y tambien se puede aplicar a matrices recibiendo de manera opcional los paramentros '0' columnas y '1' filas

In [35]:
np.median(arr)

11.0

In [36]:
np.median(matriz,1)

array([ 8., 18.])

stp lo usamos para conocer la desviacion estandard.Se utiliza para calcular la variación o dispersión en la que los puntos de datos individuales difieren de la media. y tambien se puede aplicar a matrices recibiendo de manera opcional los paramentros '0' columnas y '1' filas

In [37]:
np.std(arr)

5.040833264451424

In [40]:
np.std(matriz,0)

array([4. , 5. , 5. , 4.5, 5. ])

In [45]:
np.std(matriz,1)

array([1.49666295, 2.0976177 ])

var sirve para sacar la varianza, y tambien se puede aplicar a matrices recibiendo de manera opcional los paramentros '0' columnas y '1' filas

La varianza es una medida de dispersión que representa la variabilidad de una serie de datos con respecto a su media. Formalmente, se calcula como la suma de los cuadrados de los residuos dividida por las observaciones totales.

También puede calcularse como la desviación estándar al cuadrado. Por cierto, entendemos el residuo como la diferencia entre el valor de una variable a la vez y el valor medio de toda la variable.

In [41]:
np.var(arr)

25.410000000000004

In [43]:
np.var(matriz,0)

array([16.  , 25.  , 25.  , 20.25, 25.  ])

In [44]:
np.var(matriz,1)

array([2.24, 4.4 ])

la media la podemos calcular con mean y tambien se puede aplicar a matrices recibiendo de manera opcional los paramentros '0' columnas y '1' filas

In [46]:
np.mean(arr)

12.3

In [47]:
np.mean(matriz,0)

array([ 9. , 12. , 13. , 13.5, 14. ])

In [48]:
np.mean(matriz,1)

array([ 7.6, 17. ])

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [64]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [76]:
a.ndim
b.ndim

1

In [77]:
b = np.expand_dims(b,axis=0)

In [78]:
b.ndim

2

In [79]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

T es transpuesta y sirve para concatenar a manera de filas sin el error que se genera por el segundo array ya que este cuenta con una sola fila.

En resumen, np.concatenate((a, b.T), axis=1) funciona porque la transposición de b ajusta sus dimensiones para que sean compatibles con las de a en la concatenación a lo largo del eje 1.

In [83]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])