In [1]:
import numpy as np

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Este es un error al querer cambiar un array sin modificar el original ya que aunque hacemos el cambio dentro de otra variable sigue haciendo referencia al original y hace la modificacion dentro del array original dañandolo

In [9]:
trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

Usando copy evitamos se reescriba en el array original. se puede usar con array, matriz y tensor

In [11]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])