In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Si los valores de arr son mayores a 5 retorna true

In [4]:
indices_de_condicion =arr > 5
indices_de_condicion


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Aqui al pasarle los indices_de_condicion me da solo los valores que fueron verdaderos

In [6]:
arr[indices_de_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

Si los valores de arr son mayores a 5 retorna y menores a 9 

In [8]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Si cumple la condicion de ser mayor que 5 sera reemplazado por 90

In [9]:
arr[arr > 5] = 90

In [10]:
arr[arr== 90]

array([90, 90, 90, 90, 90], dtype=int8)