In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

De esta manera duplica los valores que tiene la lista

In [4]:
lista * 2

[1, 2, 1, 2]

In [5]:
arr =np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
1 / arr

/tmp/ipykernel_89272/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [15]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Explicación:

matriz es de dimensiones (2, 5).
matriz2.T es de dimensiones (5, 2).
El producto de matriz y matriz2.T resulta en una nueva matriz de dimensiones (2, 2).
El cálculo del producto de matrices se realiza como sigue:

El elemento en la posición (i, j) del resultado es la suma del producto de los elementos correspondientes de la i-ésima fila de la primera matriz y la j-ésima columna de la segunda matriz.
Para el elemento (0, 0):

(0∗0)+(1∗1)+(2∗2)+(3∗3)+(4∗4)=0+1+4+9+16=30
Para el elemento (0, 1):
(0∗5)+(1∗6)+(2∗7)+(3∗8)+(4∗9)=0+6+14+24+36=80
Para el elemento (1, 0):
(5∗0)+(6∗1)+(7∗2)+(8∗3)+(9∗4)=0+6+14+24+36=80
Para el elemento (1, 1):
(5∗5)+(6∗6)+(7∗7)+(8∗8)+(9∗9)=25+36+49+64+81=255
Por lo tanto, el resultado de np.matmul(matriz, matriz2.T) es:

[30 80
80 255]


Los dos metodos siguientes dan el mismo resultado, hacen el mismo calculo

In [21]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [22]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])